### ISSUE TITLE
Add strict_types

### ISSUE THREAD

**Issue by theking2** [WordPress/wpcs-docs#137]
Include the inclusion of `declare(strict_types=1);` in the standards.

It uses modern PHP features prevents errors early on and is a good standard.

**Comment by jrfnl** [comment]
Thanks for the suggestion.

While this repo maintains the handbook _containing_ the WordPress Coding standards, it is not the place where decisions are taken about the _contents_ of the handbook.

New coding standards have to be proposed via a post on Make.wordpress.org and have to be met with significant approval from committers before they will be accepted. After acceptance, the handbook is updated (and then the automated tooling too).

Having said that, the chances of a proposal to add a `declare(strict_types=1);` requirement to the standards being accepted, is, in my opinion, very very slim.

`declare(strict_types=1);` is most effective when **all** code in an ecosystem uses it. That includes plugins and themes, block patterns etc.
If even one file doesn't use it, its effect is contrary as it will lead to really hard to debug bugs due to the one-way type juggling.

Also, as the WP codebase is largely legacy code which relies heavily on the PHP type juggling semantics, it is likely that adding `strict_types` would require a lot of chances in WP itself, including a lot of changes to function signatures, which would be considered breaking changes and breaking changes are not accepted in WP (at least not for the WP Core code).

Closing as opened in the wrong place.
